application: doceditor-webapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /static/docs/
  mime_type: text/plain
  static_dir: app/docs

- url: /static/docs
  mime_type: text/plain
  static_dir: app/docs

- url: /lib
  static_dir: lib

- url: .*
  script: main.app
